### DISCUSSION TITLE
Prefix not stripped from version tag

### DISCUSSION THREAD

**Discussion by JonasDoe** [tj-actions/branch-names#254] [Q&A] [answered]
Hey, since I can't imagine that being a bug nobody noticed yet, here's my issue in a discussion. ;) I basically try to get the version tag from `steps.branch-name.outputs.tag`, but instead of, say, `0.7.27`, I end up with something like `refs/tags/v0.7.27`.
Here's the beginning of my workflow file:
```yaml
name: Publish docker image for release
on:
  release:
    types: [published]

jobs:
  generate:
    name: Create release docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.3
        with:
          strip_tag_prefix: true
      - name: Print version
        run: echo ${DOCKER_TAG} # Prints refs/tags/v0.7.27 instead of 0.7.27
        env:
          DOCKER_TAG: ${{ steps.branch-name.outputs.tag }}
...
```
Am I doing something wrong? Thank you in advance!
