### ISSUE TITLE
Add support for checking default branch and non default branches

### ISSUE THREAD

**Issue by jackton1** [tj-actions/branch-names#10]
* branch-name:

### Description

Ideally this would be a boolean output the gets the current branch and returns true if the ref is the default branch or not

```yaml

if: steps.branch_name.outputs.is_default
run: |
  echo "This is currently running on the default branch"

if: !steps.branch_name.outputs.is_default
run: |
  echo "This is currently running on a non default branch"

```

### What I Did

Getting annoyed with the current process of detecting the branch.
